### PR TITLE
Add getter for session tokens

### PR DESCRIPTION
**Pull request by benoit-apk**

### CODE REVIEW

**Comment by ddattee** [comment]
Hi,
thanks for contributing.
I was wondering what was the need behind retrieving the token ?
Everything seem ok to us it's just for understanding the need.
Thanks

**Comment by benoit-apk** [comment]
Hi,

Actually, we would like to provide the user with the possibility to create an account by entering the corresponding name and password, in case he wouldn't (yet) know which token to use.
This is mainly for the sake of completeness, but it could also save a bit of time for some merchants.

**Comment by ddattee** [comment]
Ok thanks for the answer.

Do you need this PR to continue testing or can you use the current release to keep testing ? 
We would like to avoid doing too small releases if we can.

**Comment by benoit-apk** [comment]
We can continue testing for now with the current release ;)

**Pull request merged**
